config/routes.rb
Rails.application.routes.draw do
  root 'starships#index'
  resources :starships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crew_member.rb
class CrewMember < ApplicationRecord
	belongs_to :starship
	
end

app/models/starship.rb
class Starship < ApplicationRecord
	has_many :crew_members
	accepts_nested_attributes_for :crew_members,
	  reject_if: lambda { |attributes| attributes["name"].blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
  before_action :set_starship, only: [:show, :edit, :update, :destroy]

  # GET /starships
  # GET /starships.json
  def index
    @starships = Starship.all
  end

  # GET /starships/1
  # GET /starships/1.json
  def show
  end

  # GET /starships/new
  def new
    @starship = Starship.new
    3.times { @starship.crew_members.build }
  end

  # GET /starships/1/edit
  def edit
  end

  # POST /starships
  # POST /starships.json
  def create
    @starship = Starship.new(starship_params)

    respond_to do |format|
      if @starship.save
        format.html { redirect_to @starship, notice: 'Starship was successfully created.' }
        format.json { render :show, status: :created, location: @starship }
      else
        format.html { render :new }
        format.json { render json: @starship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /starships/1
  # PATCH/PUT /starships/1.json
  def update
    respond_to do |format|
      if @starship.update(starship_params)
        format.html { redirect_to @starship, notice: 'Starship was successfully updated.' }
        format.json { render :show, status: :ok, location: @starship }
      else
        format.html { render :edit }
        format.json { render json: @starship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /starships/1
  # DELETE /starships/1.json
  def destroy
    @starship.destroy
    respond_to do |format|
      format.html { redirect_to starships_url, notice: 'Starship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_starship
      @starship = Starship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def starship_params
      params.require(:starship).permit(:name, crew_members_attributes: [:starship_id, 
        :name, :division])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/starships_helper.rb
module StarshipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sbdd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/starships/_form.html.erb
<%= form_with(model: starship, local: true) do |form| %>
  <% if starship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(starship.errors.count, "error") %> prohibited this starship from being saved:</h2>

      <ul>
      <% starship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  Crew Members:

  <ul>
    <%= fields_for :crew_members do |cm| %>
      <li>
        <%= cm.label :name %>
        <%= cm.text_field :name %>
        <%= cm.label :division %>
        <%= cm.select(:division, ["Command", "Engineering", "Science"]) %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/starships/edit.html.erb
<h1>Editing Starship</h1>

<%= render 'form', starship: @starship %>

<%= link_to 'Show', @starship %> |
<%= link_to 'Back', starships_path %>

app/views/starships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Starships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @starships.each do |starship| %>
      <tr>
        <td><%= starship.name %></td>
        <td><%= link_to 'Show', starship %></td>
        <td><%= link_to 'Edit', edit_starship_path(starship) %></td>
        <td><%= link_to 'Destroy', starship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Starship', new_starship_path %>

app/views/starships/new.html.erb
<h1>New Starship</h1>

<%= render 'form', starship: @starship %>

<%= link_to 'Back', starships_path %>

app/views/starships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @starship.name %>
  <strong>Crew Members:</strong>
    <% @starship.crew_members.each do |cm| %>
    	<%= cm.name %>
    <% end %>
</p>

<%= link_to 'Edit', edit_starship_path(@starship) %> |
<%= link_to 'Back', starships_path %>